Juan/Juan/Models/ProductSize.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Juan.Models
{
    public class ProductSize : BaseEntity
    {
        public string Size { get; set; }
    }
}

Juan/Juan/Areas/AdminArea/Controllers/ProductSizeController.cs
using Juan.Data;
using Juan.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Juan.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    [Authorize(Roles = "SuperAdmin,Admin")]
    public class ProductSizeController : Controller
    {
        private readonly AppDbContext _context;

        public ProductSizeController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<ProductSize> productSizes = await _context.ProductSizes
                .Where(m => !m.IsDeleted)
                .ToListAsync();

            return View(productSizes);
        }




        [HttpGet]
        [Authorize(Roles = "SuperAdmin")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductSize productSize)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }


                bool isExist = await _context.ProductSizes.AnyAsync(m => m.Size.Trim() == productSize.Size.Trim());

                if (isExist)
                {
                    ModelState.AddModelError("size", "size already exist");
                    return View();
                }


                await _context.ProductSizes.AddAsync(productSize);

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                ViewBag.Message = ex.Message;
                return View();
            }

        }

        [HttpGet]
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null) return BadRequest();

            ProductSize productSize = await _context.ProductSizes.FindAsync(id);

            if (productSize == null) return NotFound();

            return View(productSize);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            ProductSize productSize = await _context.ProductSizes.FirstOrDefaultAsync(m => m.Id == id);

            productSize.IsDeleted = true;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                if (id is null) return BadRequest();

                ProductSize productSize = await _context.ProductSizes.FirstOrDefaultAsync(m => m.Id == id);

                if (productSize is null) return NotFound();

                return View(productSize);

            }
            catch (Exception ex)
            {

                ViewBag.Message = ex.Message;
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ProductSize productSize)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(productSize);
                }

                ProductSize dbProductSize = await _context.ProductSizes.AsNoTracking().FirstOrDefaultAsync(m => m.Id == id);

                if (dbProductSize is null) return NotFound();

                if (dbProductSize.Size.ToLower().Trim() == productSize.Size.ToLower().Trim())
                {
                    return RedirectToAction(nameof(Index));
                }

                //dbCategory.Name = category.Name;

                _context.ProductSizes.Update(productSize);

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {

                ViewBag.Message = ex.Message;
                return View();
            }
        }
    }
}

Juan/Juan/Areas/AdminArea/Views/ProductSize/Create.cshtml
@model ProductSize
@{
    ViewData["Title"] = "Create";
}

<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <span class="text-danger">@ViewBag.Message</span>
            <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <p class="card-description">
                            Category
                        </p>
                        <form asp-controller="ProductSize" asp-action="Create" class="forms-sample" method="post">
                            <div class="form-group">
                                <label for="exampleInputUsername1">Color</label>
                                <input maxlength="" minlength="" type="text" class="form-control" asp-for="Size">
                                <span class="text-danger my-1" asp-validation-for="Size"></span>
                            </div>
                            <button type="submit" class="btn btn-primary mr-2">Submit</button>
                            <a asp-controller="ProductSize" asp-action="Index" class="btn btn-light">Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationPartial" />


}

Juan/Juan/Areas/AdminArea/Views/ProductSize/Detail.cshtml
@model ProductSize
@{
    ViewData["Title"] = "Detail";
}

<div class="container my-5">
    <div class="card">
        <div class="card-header">
            Category detail 
        </div>
        <div class="card-body">
            <p class="card-text">@Model.Size</p>
        </div>
    </div>
</div>

Juan/Juan/Areas/AdminArea/Views/ProductSize/Edit.cshtml
@model ProductSize

@{
    ViewData["Title"] = "Edit";
}

<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <span class="text-danger">@ViewBag.Message</span>
            <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <p class="card-description">
                            Size
                        </p>
                        <form asp-controller="ProductSize" asp-action="Edit" class="forms-sample" method="post">
                            <div class="form-group">
                                <label for="exampleInputUsername1">Name</label>
                                <input maxlength="" minlength="" type="text" class="form-control" asp-for="Size">
                                <span class="text-danger my-1" asp-validation-for="Size"></span>
                            </div>
                            <button type="submit" class="btn btn-primary mr-2">Submit</button>
                            <a asp-controller="ProductSize" asp-action="Index" class="btn btn-light">Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{

  <partial name="_ValidationPartial"/>
}

Juan/Juan/Areas/AdminArea/Views/ProductSize/Index.cshtml
@model IEnumerable<ProductSize>

<div class="container-fluid my-3 mx-3">
    <div class="table-responsive pt-3">
        <div class="create-btn mb-3">
            @if (User.IsInRole("SuperAdmin"))
            {
                <a asp-controller="ProductSize" asp-action="Create" class="btn btn-success"><i class="fa-solid fa-plus"></i></a>
            }
        </div>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>
                        Size
                    </th>
                    <th style="text-align: center;">
                        Settings
                    </th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                    <tr>


                        <td>
                            <Span>@item.Size</Span>
                        </td>
                        <td style="text-align: center;">
                            <a asp-action="Detail" asp-route-id="@item.Id" class="btn btn-info"><i class="mdi mdi-information mx-0 text-white"></i></a>
                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary"><i class="mdi mdi-table-edit"></i></a>
                            <form style="display: inline-block;" asp-action="Delete" asp-route-id="@item.Id" method="post">
                                <button type="submit" class="btn btn-danger"><i class="mdi mdi-delete-forever"></i></button>
                            </form>
                        </td>

                    </tr>
                }


            </tbody>
        </table>
    </div>
</div>